### ISSUE TITLE
link to working examples

### ISSUE THREAD

**Issue by guaka** [simple-sidebar/simpler-sidebar#26]
I would love to see this in action without too much hassle (i.e. without doing `git clone`, instead just a link to something like http://jillix.github.io/jQuery-sidebar/), ideally the link is somewhere at the top of `README.md`.

**Comment by dcdeiv** [comment]
Yeah, I am working on it. Actually at this [repo](https://github.com/simple-sidebar/sidebarbones-jekyll). I will make a github page for this repo ASAP!!

**Comment by dcdeiv** [comment]
I am working really ahrd to make a working github page for this repo. But since I have a full-time job, the development is slow. Everyday, as soon as I have some time to work on it, I will push new demos.

This is what I have done by now, and you can check it out at its Github page [https://simple-sidebar.github.io/simpler-sidebar](https://simple-sidebar.github.io/simpler-sidebar)

**Comment by dcdeiv** [comment]
## Demos
- [ ] static right
- [ ] static right top
- [ ] static left
- [ ] static left top
- [ ] dynamic right
- [ ] dynamic right top
- [ ] dynamic left
- [ ] dynamic left top
- [ ] init: opened
- [ ] custom width
- [ ] hidden mask
- [ ] allow scroll
- [ ] custom functions
- [ ] multiple instances
- [ ] multiple instances with custom functions
