### ISSUE TITLE
any animation in the side panel causes it to close

### ISSUE THREAD

**Issue by ericandrewscott** [simple-sidebar/simpler-sidebar#30]
- [x] I have carefully read the [README.md](https://github.com/simple-sidebar/simpler-sidebar/blob/master/README.md) file
- [x] I have installed the [latest](https://github.com/simple-sidebar/simpler-sidebar/releases/latest) version
  - [ ] I have downloaded the plugin with `github`
  - [ ] I have downloaded the plugin with `npm` - `npm install simpler-sidebar`
  - [x] I have downloaded the plugin with `bower` - `bower install simpler-sidebar`
- [x] I have migrated from **v1.x.x** to **v2.x.x**
  - [x] I have carefully read the [RELEASES.md](https://github.com/simple-sidebar/simpler-sidebar/blob/master/doc/RELEASES.md) file in the `doc` folder
  - [x] I have carefully read the *latest changelog* file in the [doc/changelog](https://github.com/simple-sidebar/simpler-sidebar/tree/master/doc/changelogs) folder
  - [x] I have carefully read the [OPTIONS.md](https://github.com/simple-sidebar/simpler-sidebar/blob/master/doc/OPTIONS.md) file in the `doc` folder
  - [ ] I don't understand how to migrate
- [x] I have found a bug
  - [ ] I am using jQuery v1.x.x
  - [ ] I am using jQuery v2.x.x
  - [x] I am using jQuery v3.x.x
- [ ] I want to suggest a new feature
  - [ ] I have carefully read the [CONTRIBUTING.md](https://github.com/simple-sidebar/simpler-sidebar/blob/master/CONTRIBUTING.md) file
  - [ ] I have followed the coding style conventions I saw in files
    - [ ] I have used the `editorconfig` plugin in my editor
    - [ ] I have used the `jscs` plugin in my editor
    - [ ] I have used the `jshint` plugin in my editor
  - [ ] I have run `grunt lint` to test if I made some mistakes
  - [ ] I have run `grunt build` to apply changes
  - [ ] I have tested the plugin by using the `demo` folder on my computer

## Actual behavior
When placing any other Javascript (in this case Bootstrap's collapse) with animations in the side panel, taking an action that fires any animation closes the simpler-sidebar

## Steps to reproduce the behavior
Place any jQuery driven animation in the simpler-sidebar

## Expected behavior
Only clicking on the ``quitter`` selector or on the mask should close simpler-sidebar

## Demo of actual behavior
http://screencast.com/t/ERiZhBsT219p

**Comment by dcdeiv** [comment]
Please, take your time to answer these questions, a live demo would help too!

- [ ] I have carefully read the [README.md](https://github.com/simple-sidebar/simpler-sidebar/blob/master/README.md) file
- [ ] I have installed the [latest](https://github.com/simple-sidebar/simpler-sidebar/releases/latest) version
  - [ ] I have downloaded the plugin with `github`
  - [ ] I have downloaded the plugin with `npm` - `npm install simpler-sidebar`
  - [ ] I have downloaded the plugin with `bower` - `bower install simpler-sidebar`
- [ ] I have migrated from **v1.x.x** to **v2.x.x**
  - [ ] I have carefully read the [RELEASES.ms](https://github.com/simple-sidebar/simpler-sidebar/blob/master/doc/RELEASES.md) file in the `doc` folder
  - [ ] I have carefully read the *latest changelog* file in the [doc/changelog](https://github.com/simple-sidebar/simpler-sidebar/tree/master/doc/changelogs) folder
  - [ ] I have carefully read the [OPTIONS.ms](https://github.com/simple-sidebar/simpler-sidebar/blob/master/doc/OPTIONS.md) file in the `doc` folder
  - [ ] I don't understand how to migrate
- [ ] I have found a bug
  - [ ] I am using jQuery v1.x.x
  - [ ] I am using jQuery v2.x.x
  - [ ] I am using jQuery v3.x.x
- [ ] I want to suggest a new feature
  - [ ] I have carefully read the [CONTRIBUTING.md](https://github.com/simple-sidebar/simpler-sidebar/blob/master/CONTRIBUTING.md) file
  - [ ] I have followed the coding style conventions I saw in files
    - [ ] I have used the `editorconfig` plugin in my editor
    - [ ] I have used the `jscs` plugin in my editor
    - [ ] I have used the `jshint` plugin in my editor
  - [ ] I have run `grunt lint` to test if I made some mistakes
  - [ ] I have run `grunt build` to apply changes
  - [ ] I have tested the plugin by using the `demo` folder on my computer

## Actual behavior

## Steps to reproduce the behavior

## Expected behavior

**Comment by ericandrewscott** [comment]
Sorry @dcdeiv ... I have updated my original comment.

**Comment by dcdeiv** [comment]
Are you sure you've upgraded to the latest version? I know bower has some strange problems upgrading to the latest version if it is a major release and sometimes it happens to minors too.
I am asking because I had the same problem with bower and had to reinstall the package.

I have actually fixed this bug with the [f3aaddf](https://github.com/simple-sidebar/simpler-sidebar/commit/f3aaddfb6115547ea3db40ee65225a385518e93f) commit. This commit was included in [v2.0.4](https://github.com/simple-sidebar/simpler-sidebar/releases/tag/v2.0.4) release, and in its [changelog](https://github.com/simple-sidebar/simpler-sidebar/blob/master/doc/changelogs/v2.0.4.md#1---fixed-quitter-selector) I am mentioning the same behavior that your package has!

By now the latest release is the [v2.1.4](https://github.com/simple-sidebar/simpler-sidebar/releases/tag/v2.1.4) which fix #27 and officially adds jquery v2.x.x and v3.x.x. I guess you should have updated to this version!

1 - Can you please post me the entire header shipped with the version you are using?
The latest header is:
```javascript
/*! simpler-sidebar v2.1.4 (https://github.com/simple-sidebar/simpler-sidebar#readme)
** Copyright (c) 2015 - 2016 Davide Di Criscito
** Dual licensed under MIT and GPL-2.0
*/
```

2 - Please, copy and paste line **82** and line **251** of the `dist/jquery.simpler-sidebar.js` file delivered with the bower package you installed. If you installed the latest version, those two lines should be:
```
82 | quitter = ( !cfg.selectors.quitter ) ? "a" : cfg.selectors.quitter
...
251| $sidebar.on( "click", quitter, animateClose );
```

3 - Are you using any custom event? [events](https://github.com/simple-sidebar/simpler-sidebar/blob/master/doc/OPTIONS.md#events
You are using the [events.callbacks.animation.freezePage](https://github.com/simple-sidebar/simpler-sidebar/blob/master/doc/OPTIONS.md#eventscallbacksanimationfreezepage) but that worked since ever and it hasn't changed.

4 - Can you please test it with another jQuery version?

**Comment by ericandrewscott** [comment]
@dcdeiv you're right. I had my bower file set to latest major revision (``"simpler-sidebar": "^2.1.4"``), but it was stuck on ``2.0.2``.  Bower update wasn't working. That's annoying. I removed the ref, rebuilt, added it back, rebuilt, and now it works. Thanks!

**Comment by dcdeiv** [comment]
You're welcome! :+1:

**Comment by ericandrewscott** [comment]
@dcdeiv I've been meaning to tell you that the changes you made in version 2 are pretty spectacular. Simpler-sidebar is pretty lightweight and slick!

**Comment by dcdeiv** [comment]
Thank you very much! This is the very first feedback I receive! I really appreciate that you like this plugin!
